services:
  reverse-proxy:
    restart: unless-stopped
    image: traefik:v2.10
    networks:
      - backend
    command:
      - "--entrypoints.web.address=:80"
      - "--providers.docker"
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    restart: always
    build: ./backend
    depends_on:
      - database
    networks:
      - backend
    volumes:
      - ./backend/server:/srv
      - user-data:/var/data/user-data
      - app-data:/var/data/app-data
    env_file: .env
    environment:
      - MLFLOW_AUTH_CONFIG_PATH=/srv/auth_config.ini
    expose:
      - 5000
    labels:
      traefik.http.routers.backend.rule: Host(`${DOMAIN}`) && ~PathPrefix(`/signup`)

  database:
    image: postgres:latest
    restart: always
    user: postgres
    volumes:
      - app-data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME:?DATABASE_NAME is not set}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?DATABASE_PASSWORD is not set}
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:

volumes:
  user-data:
  app-data: