services:

  backend:
    command:
      - server
      - --backend-store-uri=postgresql://postgres:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME}
      - --default-artifact-root=/mlruns
      - --host=0.0.0.0
      - --port=5000
      - --dev
