services:
  mlflow:
    command:
      - server
      - --backend-store-uri=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      # - --registry-store-uri=<URI>
      # - --default-artifact-root=<URI>
      # - --serve-artifacts
      # - --no-serve-artifacts
      # - --artifacts-only
      - --artifacts-destination=/mlruns
      - --host=0.0.0.0
      - --port=5000
      # - --workers=<workers>
      # - --static-prefix=<static_prefix>
      # - --gunicorn-opts=<gunicorn_opts>
      # - --waitress-opts=<waitress_opts>
      # - --expose-prometheus=<expose_prometheus>
      - --app-name=basic-auth
      - --dev
    ports:
      - "5000:5000"

  database:
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
