services:

  proxy:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      - backend
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

  backend:
    restart: always
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    depends_on:
      - db
    networks:
      - backend
    environment:
    command: mlflow server --backend-store-uri mysql+pymysql://${}:${}@db:3306/${} --default-artifact-root s3://mlflow/ --host 0.0.0.0

  db:
    image: postgre:latest
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:


volumes:
  database_data:


secrets:
  db-password:
    file: ./db-password.txt
